name: Deploy to Railway (Docker)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Build Docker image
        run: docker build -t pokemon-app:${{ github.sha }} .

      - name: Deploy to Railway 
        run: |
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
