name: Deploy to Railway

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Set Railway Token
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: echo "RAILWAY_TOKEN=${RAILWAY_TOKEN}" >> $GITHUB_ENV

      - name: Link to Railway project
        run: railway link --project ${{ secrets.RAILWAY_PROJECT }}

      - name: Deploy to Railway
        run: railway up

